# Generated by Django 6.0.6 on 2026-06-13 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_returned',
        ),
    ]
